import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossOrigin="anonymous" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
            </Head>
            <main>
                <header>
                    <nav className="navbar bg-body-tertiary">
                        <div className="container-fluid">
                            <a className="navbar-brand">Shop <i className="fa fa-shopping-bag" aria-hidden="true"></i>
                            </a>
                            <form className="d-flex" role="search">
                                <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                            </form>
                        </div>
                    </nav>
                </header>
                <section>
                    <div className="container">
                        <div className="container bg-white">
                            <nav className="navbar navbar-expand-md navbar-light bg-white">
                                <div className="container-fluid p-0"> <a className="navbar-brand text-uppercase fw-800" href="#"><span className="border-red pe-2">New</span>Product</a> <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#myNav" aria-controls="myNav" aria-expanded="false" aria-label="Toggle navigation"> <span className="fas fa-bars"></span> </button>
                                </div>
                            </nav>
                            <div className="row">
                                <div className="col-lg-3 col-sm-6 d-flex flex-column align-items-center justify-content-center product-item my-3">
                                    <div className="product"> <Image height='200' width="200" src="https://images.pexels.com/photos/54203/pexels-photo-54203.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="" />
                                        <ul className="d-flex align-items-center justify-content-center list-unstyled icons">
                                            <li className="icon"><span className="fas fa-expand-arrows-alt"></span></li>
                                            <li className="icon mx-3"><span className="far fa-heart"></span></li>
                                            <li className="icon"><span className="fas fa-shopping-bag"></span></li>
                                        </ul>
                                    </div>
                                    <div className="tag bg-red">sale</div>
                                    <div className="title pt-4 pb-1">Winter Sweater</div>
                                    <div className="d-flex align-content-center justify-content-center"> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> </div>
                                    <div className="price">$ 60.0</div>
                                </div>
                                <div className="col-lg-3 col-sm-6 d-flex flex-column align-items-center justify-content-center product-item my-3">
                                    <div className="product"> <Image height='320' width='320' src="https://images.pexels.com/photos/6764040/pexels-photo-6764040.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="" />
                                        <ul className="d-flex align-items-center justify-content-center list-unstyled icons">
                                            <li className="icon"><span className="fas fa-expand-arrows-alt"></span></li>
                                            <li className="icon mx-3"><span className="far fa-heart"></span></li>
                                            <li className="icon"><span className="fas fa-shopping-bag"></span></li>
                                        </ul>
                                    </div>
                                    <div className="tag bg-black">out of stock</div>
                                    <div className="title pt-4 pb-1">Denim Dresses</div>
                                    <div className="d-flex align-content-center justify-content-center"> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> </div>
                                    <div className="price">$ 55.0</div>
                                </div>
                                <div className="col-lg-3 col-sm-6 d-flex flex-column align-items-center justify-content-center product-item my-3">
                                    <div className="product"> <Image height='320' width='320' src="https://images.pexels.com/photos/914668/pexels-photo-914668.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="" />
                                        <ul className="d-flex align-items-center justify-content-center list-unstyled icons">
                                            <li className="icon"><span className="fas fa-expand-arrows-alt"></span></li>
                                            <li className="icon mx-3"><span className="far fa-heart"></span></li>
                                            <li className="icon"><span className="fas fa-shopping-bag"></span></li>
                                        </ul>
                                    </div>
                                    <div className="tag bg-green">new</div>
                                    <div className="title pt-4 pb-1"> Empire Waist Dresses</div>
                                    <div className="d-flex align-content-center justify-content-center"> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> </div>
                                    <div className="price">$ 70.0</div>
                                </div>
                                <div className="col-lg-3 col-sm-6 d-flex flex-column align-items-center justify-content-center product-item my-3">
                                    <div className="product"> <Image height='320' width='320' src="https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="" />
                                        <ul className="d-flex align-items-center justify-content-center list-unstyled icons">
                                            <li className="icon"><span className="fas fa-expand-arrows-alt"></span></li>
                                            <li className="icon mx-3"><span className="far fa-heart"></span></li>
                                            <li className="icon"><span className="fas fa-shopping-bag"></span></li>
                                        </ul>
                                    </div>
                                    <div className="title pt-4 pb-1">Pinafore Dresses</div>
                                    <div className="d-flex align-content-center justify-content-center"> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> </div>
                                    <div className="price">$ 60.0</div>
                                </div>
                            </div>
                            <div className="row">
                                <div className="col-lg-3 col-sm-6 d-flex flex-column align-items-center justify-content-center product-item my-3">
                                    <div className="product"> <Image height='320' width='320' src="https://hellbunny.com/media/catalog/product/h/l/hlb40006-wonder-years-pinafore-dress-mustard-01_1_1.jpg?width=700&height=700&store=default&image-type=image" alt="" />
                                        <ul className="d-flex align-items-center justify-content-center list-unstyled icons">
                                            <li className="icon"><span className="fas fa-expand-arrows-alt"></span></li>
                                            <li className="icon mx-3"><span className="far fa-heart"></span></li>
                                            <li className="icon"><span className="fas fa-shopping-bag"></span></li>
                                        </ul>
                                    </div>
                                    <div className="tag bg-red">sale</div>
                                    <div className="title pt-4 pb-1">Vintage Pinafore Dress</div>
                                    <div className="d-flex align-content-center justify-content-center"> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> </div>
                                    <div className="price">$ 60.0</div>
                                </div>
                                <div className="col-lg-3 col-sm-6 d-flex flex-column align-items-center justify-content-center product-item my-3">
                                    <div className="product"> <Image height='320' width='320' src="https://cdn-img.prettylittlething.com/2/0/b/f/20bf613769d11f84592c7f290f9c10aaca50d345_CLQ3250_1.JPG?imwidth=300" alt="" />
                                        <ul className="d-flex align-items-center justify-content-center list-unstyled icons">
                                            <li className="icon"><span className="fas fa-expand-arrows-alt"></span></li>
                                            <li className="icon mx-3"><span className="far fa-heart"></span></li>
                                            <li className="icon"><span className="fas fa-shopping-bag"></span></li>
                                        </ul>
                                    </div>
                                    <div className="tag bg-black">out of stock</div>
                                    <div className="title pt-4 pb-1">Martin Black Dress</div>
                                    <div className="d-flex align-content-center justify-content-center"> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> </div>
                                    <div className="price">$ 55.0</div>
                                </div>
                                <div className="col-lg-3 col-sm-6 d-flex flex-column align-items-center justify-content-center product-item my-3">
                                    <div className="product"> <Image height='320' width='320' src="http://cdn.shopify.com/s/files/1/0313/1572/2378/products/linen-pinafore-dress-no-32-in-emmeline-check-pyne-and-smith-3.jpg?v=1651860592" alt="" />
                                        <ul className="d-flex align-items-center justify-content-center list-unstyled icons">
                                            <li className="icon"><span className="fas fa-expand-arrows-alt"></span></li>
                                            <li className="icon mx-3"><span className="far fa-heart"></span></li>
                                            <li className="icon"><span className="fas fa-shopping-bag"></span></li>
                                        </ul>
                                    </div>
                                    <div className="title pt-4 pb-1"> Linen pinafore dress</div>
                                    <div className="d-flex align-content-center justify-content-center"> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> </div>
                                    <div className="price">$ 70.0</div>
                                </div>
                                <div className="col-lg-3 col-sm-6 d-flex flex-column align-items-center justify-content-center product-item my-3">
                                    <div className="product"> <Image height='320' width='320' src="https://www.lulus.com/images/product/xlarge/9585181_1968196.jpg?w=375&hdpi=1" alt="" />
                                        <ul className="d-flex align-items-center justify-content-center list-unstyled icons">
                                            <li className="icon"><span className="fas fa-expand-arrows-alt"></span></li>
                                            <li className="icon mx-3"><span className="far fa-heart"></span></li>
                                            <li className="icon"><span className="fas fa-shopping-bag"></span></li>
                                        </ul>
                                    </div>
                                    <div className="tag bg-green">new</div>
                                    <div className="title pt-4 pb-1">Pinafore Mini Dress</div>
                                    <div className="d-flex align-content-center justify-content-center"> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> <span className="fas fa-star"></span> </div>
                                    <div className="price">$ 60.0</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </>
    )
}
